export const cancel = 'Cancel'
export const helloMessage = 'Hello, '
export const homeString = 'Home'
export const login = 'Login'
export const search = 'Search'
export const searchfieldLabel = 'Searchfield'
export const scroll = 'Scroll'
export const more = 'More'
export const signinGithub = 'In with Github'
export const signOutString = 'Sign Out'
export const organizationSearch = 'Organization search'
export const signOutError = 'Sign Out Error'
export const logoutBeforeRemoving =
  'To remove your account you need to sign out and login again.'
export const removeMessage = 'Account was deleted!'
export const deleteAccount = 'Delete Account'
export const removeAccount = 'Remove Account'
export const removeAccountConfirmation =
  'Are you sure you want to delete your account and all your data?'
export const signOutConfirmation = 'Are you sure you want to sign out?'
export const oAuthMessage =
  'Only OAuth Apps you authorized in your Github account can be searched for.'
export const noOrganizationError = 'No organization filled in.'
export const notFoundError = "Page wasn't found"
export const footerMessageFirst = 'Kyle @'
export const footerMessageSecond = '- Github GraphQL project'
export const checkOnGithub = 'Check on github'
export const owner = 'Owner: '
export const unstar = 'Unstar'
export const star = 'Star'
export const watch = 'Watch'
export const unwatch = 'Unwatch'
export const repositoriesString = 'Repositories'
